### ISSUE TITLE
update via FHEM geht nicht

### ISSUE THREAD

**Issue by sidey79** [Ralf9/10_IT#1]
Hi Ralf,

update all bzw. update force vom IT Modul klappt nicht.
Liegt vielleicht daran, dass Du die controls Datei wie beim signalduino benannt hast....

**Comment by Ralf9** [comment]
seltsam bei mir funktioniert es

update all https://raw.githubusercontent.com/Ralf9/test/master/controls_signalduino.txt

```
2016.05.08 01:24:04 1 : UPD FHEM/10_IT.pm
2016.05.08 01:24:04 1 :
2016.05.08 01:24:04 1 : New entries in the CHANGED file:
2016.05.08 01:24:04 1 : 04.05.2016
2016.05.08 01:24:04 1 : - jetzt werden auch die Philips SBC und FreeTec Funksteckdosen unterstützt
2016.05.08 01:24:04 1 : 10.04.2016
2016.05.08 01:24:04 1 : - zusätzliche logs beim set
```

**Comment by sidey79** [comment]
stimmt, ist schon spät, ich habe die falsche url benutzt

https://github.com/Ralf9/test/blob/master/controls_signalduino.txt
